## Practice Problems

**Task 1 :** Create a list called 'animals' fill it with 8 of your favorite animals. Print the animal at index 2 and index 5.

<!-- Answer:

    animals = ['lion', 'giraffe', 'tiger', 'cow', 'cheetah', 'donkey', 'rabbit', 'fox']
    print(animals[2])
    print(animals[5]) -->

**Task 2 :** Create a list with numbers from 13 to 35 and print the element at index 6. Do not individually type the numbers, use the range() command.
<!-- 
Answer: 

    x = range(13,36)
    print(x[6]) -->

**Task 3 :** Using a *while loop* print all the even numbers between 2 and 56. Remember to click 'Runtime' then 'Restart runtime' if you get an "infinite loop"!

<!-- Answer: 

    x = 2
    while(x < 57):
        if(x % 2 == 0):
            print(x)
        x += 1 -->

**Task 4 :** Using the 'animal' list you made in Question 1, print all the animals using a *for loop*.

<!-- Answer: 

    animals = ['lion', 'giraffe', 'tiger', 'cow', 'cheetah', 'donkey', 'rabbit', 'fox']
    for animal in animals:
        print(animal) -->